# Generated by Django 5.2.4 on 2025-07-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("deskripsi", models.TextField()),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
